
=head1 CREDITS

=for stopwords Gustavo Leite de Mendonça Chaves

=for stopwords gnustavo

=over 4

=item L<Gustavo Leite de Mendonça Chaves|https://metacpan.org/author/GNUSTAVO> <gnustavo@cpan.org>

Many thanks to Gustavo for L<JIRA::REST|JIRA::REST>, which is what I started
working with when I first wanted to automate my interactions with JIRA in
the summer of 2016, and without which I would have had a LOT of work to do.

=back
